services:
  postgres:
    image: postgres:15
    container_name: cmdi-db
    environment:
      POSTGRES_DB: comandei
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - comandei-network

  cmdi-api:
    build: ./api
    container_name: cmdi-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cmdi-db:5432/comandei
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_FLYWAY_ENABLED: "false"
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - comandei-network
    develop:
      watch:
        - path: ./api/src
          action: rebuild
        - path: ./api/pom.xml
          action: rebuild

  cmdi-web:
    build: ./web
    container_name: cmdi-web
    ports:
      - "5173:5173"
    depends_on:
      - cmdi-api
    volumes:
      - /app/node_modules
    networks:
      - comandei-network
    develop:
      watch:
        - path: ./web/src
          action: sync
          target: /app/src
        - path: ./web/public
          action: sync
          target: /app/public
        - path: ./web/vite.config.ts
          action: sync
          target: /app/vite.config.ts
        - path: ./web/package.json
          action: rebuild
          
volumes:
  db_data:

networks:
  comandei-network:
    driver: bridge
